[project]
name = "hybrid-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pip>=25.3",
    "plotly>=6.4.0",
    "streamlit>=1.51.0",
]
